
(sdegeo:set-auto-region-naming OFF)
(sde:clear)
(sdegeo:set-auto-region-naming OFF)

(bound? (quote source))
(sdegeo:create-rectangle (position -0.005 0.0 0) (position 0.005 0.02 0) "GaSb" "source")
(bound? (quote pocket))
(sdegeo:create-rectangle (position -0.005 0.02 0) (position 0.005 0.025 0) "GaAsSb" "pocket")
(bound? (quote channel))
(sdegeo:create-rectangle (position -0.005 0.025 0) (position 0.005 0.045 0) "GaAs" "channel")
(bound? (quote drain_neck))
(sdegeo:create-rectangle (position -0.005 0.045 0) (position 0.005 0.055 0) "GaAs" "drain_neck")
(bound? (quote drain_base))
(sdegeo:create-rectangle (position -0.02 0.055 0) (position 0.02 0.07 0) "GaAs" "drain_base")
(bound? (quote substrate))
(sdegeo:create-rectangle (position -0.02 0.07 0) (position 0.02 0.08 0) "GaAs" "substrate")

(bound? (quote hfo2_left))
(sdegeo:create-rectangle (position -0.007 0.02 0) (position -0.005 0.035 0) "HfO2" "hfo2_left")
(bound? (quote sio2_left))
(sdegeo:create-rectangle (position -0.007 0.035 0) (position -0.005 0.045 0) "SiO2" "sio2_left")
(bound? (quote hfo2_right))
(sdegeo:create-rectangle (position 0.005 0.02 0) (position 0.007 0.035 0) "HfO2" "hfo2_right")
(bound? (quote sio2_right))
(sdegeo:create-rectangle (position 0.005 0.035 0) (position 0.007 0.045 0) "SiO2" "sio2_right")

(sdegeo:define-contact-set "g" 4.79 (color:rgb 0 0 1) "##")
(sdegeo:define-contact-set "d" 4.0 (color:rgb 0 1 0) "##")
(sdegeo:define-contact-set "s" 4.0 (color:rgb 1 0 0) "##")

(sdegeo:set-current-contact-set "s")
(sdegeo:set-contact (list (car (find-edge-id (position 0.0 0 0)))) "s")
(sdegeo:set-contact (list (car (find-edge-id (position 0.0 0 0)))) "s")

(sdegeo:set-current-contact-set "d")
(sdegeo:set-contact (list (car (find-edge-id (position -0.02 0.0625 0)))) "d")
(sdegeo:set-contact (list (car (find-edge-id (position -0.02 0.0625 0)))) "d")
(sdegeo:set-contact (list (car (find-edge-id (position 0.02 0.0625 0)))) "d")
(sdegeo:set-contact (list (car (find-edge-id (position 0.02 0.0625 0)))) "d")

(sdegeo:set-current-contact-set "g")
(sdegeo:set-contact (list (car (find-edge-id (position -0.007 0.0275 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position -0.007 0.0275 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position -0.007 0.04 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position -0.007 0.04 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position 0.007 0.0275 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position 0.007 0.0275 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position 0.007 0.04 0)))) "g")
(sdegeo:set-contact (list (car (find-edge-id (position 0.007 0.04 0)))) "g")

(sdedr:define-constant-profile "ConstantProfileDefinition.source" "BoronActiveConcentration" 5e+19)
(sdedr:define-constant-profile-region "ConstantProfilePlacement.source" "ConstantProfileDefinition.source" "source")
(sdedr:define-constant-profile "ConstantProfileDefinition.pocket" "PhosphorusActiveConcentration" 7e+18)
(sdedr:define-constant-profile-region "ConstantProfilePlacement.pocket" "ConstantProfileDefinition.pocket" "pocket")
(sdedr:define-constant-profile "ConstantProfileDefinition.channel" "PhosphorusActiveConcentration" 1e+15)
(sdedr:define-constant-profile-region "ConstantProfilePlacement.channel" "ConstantProfileDefinition.channel" "channel")
(sdedr:define-constant-profile "ConstantProfileDefinition.drain" "PhosphorusActiveConcentration" 5e+18)
(sdedr:define-constant-profile-region "ConstantProfilePlacement.drain1" "ConstantProfileDefinition.drain" "drain_neck")
(sdedr:define-constant-profile-region "ConstantProfilePlacement.drain2" "ConstantProfileDefinition.drain" "drain_base")
(sdedr:define-constant-profile-region "ConstantProfilePlacement.sub" "ConstantProfileDefinition.channel" "substrate")

(bound? (quote all))
(sdedr:define-refeval-window "all" "Rectangle" (position -0.025 -0.005 0) (position 0.025 0.085 0))
(sdedr:define-multibox-size "MultiboxDefinition.all" 0.005 0.005 0.002 0.002 1 1)
(sdedr:define-multibox-placement "MultiboxPlacement.all" "MultiboxDefinition.all" "all")

(bound? (quote active))
(sdedr:define-refeval-window "active" "Rectangle" (position -0.006 0.01 0) (position 0.006 0.035 0))
(sdedr:define-multibox-size "MultiboxDefinition.active" 0.001 0.001 0.0002 0.0002 1 1)
(sdedr:define-multibox-placement "MultiboxPlacement.active" "MultiboxDefinition.active" "active")

(bound? (quote tunnel))
(sdedr:define-refeval-window "tunnel_junction" "Rectangle" (position -0.006 0.018 0) (position 0.006 0.027 0))
(sdedr:define-multibox-size "MultiboxDefinition.tunnel" 0.0005 0.0005 0.0001 0.0001 1 1)
(sdedr:define-multibox-placement "MultiboxPlacement.tunnel" "MultiboxDefinition.tunnel" "tunnel_junction")

(sde:set-meshing-command "snmesh -a")
(sdedr:append-cmd-file "")
(sde:build-mesh "-a" "n@node@")
(sde:set-project-name "sdemodel")
(sdesnmesh:iocontrols "outputFile" "sdemodel")
(sde:set-meshing-command "snmesh")
(sde:set-project-name "sdemodel")
(sdesnmesh:iocontrols "outputFile" "sdemodel")
(sde:build-mesh "" "sdemodel")
